name: story_view
description: Display stories just like Whatsapp & Instagram. Can be used inline/inside ListView or Column just like Google News app. Comes with gestures to pause, forward & go to previous page.
version: 0.12.3
homepage: https://github.com/blackmann/story_view

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.2
  rxdart: ^0.27.0
  video_player: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

